# Hardware configuration for MacBook Pro (Apple Silicon)
# This file is generated by `nix-darwin` bootstrap.
# Replace this placeholder with the actual generated config.
#
# To generate: nix run nix-darwin -- --show-hardware-config
# Then save output to this file.

{ ... }: {
  # Placeholder: Replace with actual hardware configuration
  # Typical Apple Silicon Macs need:
  # system.defaults.NSGlobalDomain.AppleInterfaceStyle = "Dark";
  # system.defaults.trackpad options, etc.

  # FileVault
  # security.pam.enableSudoTouchIdAuth = true;
}
